version: "3.7"

services:
  reverse-proxy:
    image: traefik # The official Traefik docker image
    command: --api --docker # Enables the web UI and tells Traefik to listen to docker
    ports:
      - "80:80"     # The HTTP port
      - "8080:8080" # The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events

  node:
    build: 
      dockerfile: ./docker/node.dev.Dockerfile
      context: .
    labels:
      - traefik.docker.network=traefik
      - traefik.enable=true
      - traefik.frontend.rule=Host:localhost
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app
    labels:
      - traefik.enable=false
    volumes: 
      - pgdata:/var/lib/postgresql/data
    depends_on:
      - pgdata-sync

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: moorejared97@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 80
    labels:
      - traefik.docker.network=traefik
      - traefik.enable=true
      - traefik.frontend.rule=Host:pgadmin.localhost
    volumes:
      - ./docker/pga4volume:/var/lib/pgadmin
    depends_on:
      - db
  
  pgdata-sync:
    build: 
      dockerfile: pgdata-sync.Dockerfile
      context: ./docker
    labels:
      - traefik.enable=false
    volumes:
      - ./pgdata:/pgdataSync
      - pgdata:/pgdata
    command: >
     bash -c "rsync -avz /pgdataSync/. /pgdata && while true; do rsync -avz /pgdata/. /pgdataSync; sleep 60; done"

volumes:
  pgdata: